version: '3.8'

services:
  web:
    build: .
    container_name: Treevaq
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    tty: true  # ช่วยให้ container ไม่หลุด
