version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - SECRET_KEY=your-secure-secret-key # อย่าลืมเปลี่ยนเป็นคีย์ที่ปลอดภัยในการใช้งานจริง
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - GOOGLE_CLIENT_ID=your-actual-client-id
      - GOOGLE_CLIENT_SECRET=your-actual-client-secret
    volumes:
      - .:/usr/src/app # สำหรับการพัฒนา เพื่อให้โค้ดในเครื่องของคุณซิงค์กับคอนเทนเนอร์
    # ลบ 'command: ./entrypoint.sh' ออก เพราะ CMD ใน Dockerfile จะถูกใช้แทน
