services:
  web:
    build: .
    container_name: Treevaq
    volumes:
      - .:/usr/src/app  # ต้องมีนี้เพื่อ sync ไฟล์
      - ./media:/usr/src/app/media
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=myproject.settings
    tty: true