services:
  web:
    build: .
    container_name: Treevaq
    volumes:
      - .:/usr/src/app
      - ./media:/usr/src/app/media  # เพิ่มนี้
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=myproject.settings
    tty: true