# Generated by Django 4.2 on 2025-05-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_created_at_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='co2_reduction',
        ),
    ]
